AWSTemplateFormatVersion: 2010-09-09
Description: >-
  weather-app

Transform:
- AWS::Serverless-2016-10-31

Parameters:
  apiKey:
    Type: String
    Description: The API_KEY used to retrieve weather APIs
    Default: 'no-value'

Globals:
    Api:
        Cors:
            AllowMethods: "'GET,POST,OPTIONS'"
            AllowHeaders: "'content-type'"
            AllowOrigin: "'*'"
            AllowCredentials: false

Resources:

  getCities:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-cities.getCities
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Retrieve a list of Cities based on a filter.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /getCities
            Method: GET
      Environment:
        Variables:
          API_KEY: !Ref apiKey

  getWeather:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-weather.getWeather
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Retrieve a 3 days weather based on a filter.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /getWeather
            Method: GET
      Environment:
        Variables:
          API_KEY: !Ref apiKey
Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
